# To be used only for local testing

services:
  survey-bot-generator-app:
    image: survey-bot-generator-app
    ports:
      - "80:80"
    depends_on:
      - survey-bot-generator-db
      - survey-bot-generator-redis

  survey-bot-generator-db:
    build:
      context: ../
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    ports:
      - 8433:5432
    volumes:
      - survey_bot_generator_db_data:/var/lib/postgresql/data
    env_file:
      - ../.env

  survey-bot-generator-redis:
    build:
      context: ../
    image: redis:8.0-M03-alpine
    ports:
      - "6381:6379"
    env_file:
      - ../.env

volumes:
  survey_bot_generator_db_data:


